### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by sunjieemm** [TmacMai/Multimodal-Correlation-Learning#1]
https://github.com/TmacMai/Multimodal-Correlation-Learning/blob/d776fce3404ed818b96d702ed278a3946c75252a/MCL_github/modules/transformer.py#L84
I got a bug that is 'RuntimeError: Output 0 of SplitBackward0 is a view and is being modified inplace. This view is the output of a function that returns multiple views. Such functions do not allow the output views to be modified inplace. You should replace the inplace operation by an out-of-place one.'.
what should I do?  Thanks!

**Comment by TmacMai** [comment]
This is a common bug for higher version of pytorch (we use torch 1.4.0). To fix this bug, you can try to add up all the losses (e.g., main_task_loss + alpha * correlation_loss where alpha is the weight) and backward only once at each iteration instead of conducting separate backward. Also, avoid using x *= x, x+=x, etc.

**Comment by sunjieemm** [comment]
Thanks for your reply and have a good day!

**Comment by sunjieemm** [comment]
这个bug我来留个其它答案，供参考，
https://github.com/thuiar/MMSA/issues/67#issuecomment-1482289423
